server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: auth-system-id
          uri: lb://auth-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1